build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: golang-1.17
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: lint
  commands: make lint
  container:
    from: src
zz_generated_metadata:
  branch: main
  org: stolostron
  repo: acm-aap-aas-operations
